name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.3.6
        with:
          heroku_api_key: "${{ secrets.HEROKU_DEPLOY }}"
          heroku_app_name: "proffy-0" #Must be unique in Heroku
          heroku_email: "pedroca21265@gmail.com"
          appdir: "backend"
